name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    name: Generate and Deploy Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Generate documentation
        run: |
          go install golang.org/x/tools/cmd/godoc@latest
          mkdir -p docs
          godoc -http=:6060 &
          sleep 5
          wget -r -np -k -E -p -e robots=off http://localhost:6060/pkg/go-active-record/activerecord/ -P docs/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
